#!/bin/bash
boot=$HOME/distro/initrd
rm -rf $boot

mkdir -p $HOME/distro
mkdir -p $boot
mkdir -p $boot/bin
./bpsupdate
./bpskur glibc $boot/
./bpskur readline $boot/
./bpskur ncurses $boot/
./bpskur busybox $boot/
./bpskur kmod $boot/
./bpskur eudev $boot/
./bpskur util-linux $boot/
./bpskur base-file $boot/
./bpskur grub $boot/
./bpskur e2fsprogs $boot/
#****************modul yukleme*************************
mkdir -p $boot/lib/modules/
mkdir -p $boot/lib/modules/$(uname -r)
mkdir -p $boot/lib/modules/$(uname -r)/moduller
cp /lib/modules/$(uname -r)/kernel/* -prvf $boot/lib/modules/$(uname -r)/moduller/ #sistemden kopyalandı..
/sbin/depmod --all --basedir=$boot #modul indeksi oluşturluyor

#*****************initrd.img oluşturuluyor*************************
cd $boot
find |cpio -H newc -o >../initrd.img
#************************iso *********************************
mkdir -p $HOME/distro/iso
mkdir -p $HOME/distro/iso/boot
mkdir -p $HOME/distro/iso/boot/grub
mkdir -p $HOME/distro/iso/live || true

#iso dizinine vmlinuz ve initrd.img dosyamız kopyalanıyor
cp /boot/vmlinuz-$(uname -r) $HOME/distro/iso/boot/vmlinuz  #sistemde kullandığım kerneli kopyaladım istenirde kernel derlenebilir.
mv $HOME/distro/initrd.img $HOME/distro/iso/boot/initrd.img #oluşturduğumuz **initrd.img** dosyamızı taşıyoruz.

#grub menüsü oluşturuluyor..
cat > $HOME/distro/iso/boot/grub/grub.cfg << EOF
linux /boot/vmlinuz net.ifnames=0 biosdevname=0
initrd /boot/initrd.img
boot boot=live
EOF

grub-mkrescue $HOME/distro/iso/ -o $HOME/distro/distro.iso






