#!/usr/bin/env bash
depens_install()
{
source bpsbuild
echo $depends
IFS=',' read -r -a array <<< "$depends"
#liste+=("ali")
#liste+=("veli")
#array+=("bayram")
for itempaketname in "${array[@]}"
do
echo $paketname

itemindexpaket=$(cat /tmp/index.lst|grep $itempaketname)
if [ -z "${itemindexpaket}" ] #indexpaket boşsa kurulmamış demektir.
then
bpskur itempaketname
fi
done    	
}
