#!/bin/bash
rootfs="$HOME/distro/rootfs"
rm -rf $HOME/distro/iso
rm -rf $rootfs
#bash ./initrdnew
mkdir -p $HOME/distro
mkdir -p $rootfs
./bpsupdate
./bpskur glibc $rootfs
./bpskur readline $rootfs/
./bpskur ncurses $rootfs/
./bpskur \bash $rootfs/
./bpskur busybox $rootfs/
./bpskur kmod $rootfs/
./bpskur eudev $rootfs/
./bpskur util-linux $rootfs/
./bpskur \grep $rootfs/
./bpskur \sed $rootfs/

./bpskur base-file $rootfs/
./bpskur grub $rootfs/
./bpskur e2fsprogs $rootfs/
./bpskur libarchive $rootfs/

./bpskur xz $rootfs/

./bpskur curl $rootfs/
./bpskur openssl $rootfs/
./bpskur initramfs-tools $rootfs/
./bpskur \gzip $rootfs/

./bpskur coreutils $rootfs/
./bpskur acl $rootfs/
./bpskur atr $rootfs/
./bpskur gmp $rootfs/

./bpskur libselinux $rootfs/
./bpskur libsepol $rootfs/
./bpskur libsemanage $rootfs/
./bpskur mcstrans $rootfs/


./bpskur attr $rootfs/
./bpskur pcre2 $rootfs/
./bpskur findutils $rootfs/
./bpskur openrc $rootfs/
./bpskur audit $rootfs/
./bpskur pam $rootfs/
./bpskur libcap $rootfs/

./bpskur zlib $rootfs/
./bpskur zstd $rootfs/
./bpskur libxml2 $rootfs/
./bpskur brotli $rootfs/
./bpskur linux-image $rootfs/

./bpskur live-boot $rootfs/
./bpskur live-config $rootfs/

/sbin/depmod --all --basedir=$rootfs #modul indeksi oluşturluyor


#************************iso *********************************
mkdir -p $HOME/distro/iso
mkdir -p $HOME/distro/iso/boot
mkdir -p $HOME/distro/iso/boot/grub
mkdir -p $HOME/distro/iso/live || true

#### Copy kernel and initramfs (Debian/Devuan)
cp -pf $rootfs/boot/initrd.img-* $HOME/distro/iso/boot/initrd.img
cp -pf $rootfs/boot/vmlinuz-* $HOME/distro/iso/boot/vmlinuz

#### Create squashfs
mksquashfs $rootfs $HOME/distro/filesystem.squashfs -comp xz -wildcards
mv $HOME/distro/filesystem.squashfs $HOME/distro/iso/live/filesystem.squashfs
#rm -rf $rootfs/boot

#### Write grub.cfg

echo 'menuentry "Linux GNU/Linux 64-bit" --class liveiso  {' > $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinu net.ifnames=0 biosdevname=0 ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Disk GNU/Linux 64-bit" --class liveiso  {' > $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz net.ifnames=0 biosdevname=0 init=/bin/initdisk ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Live GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/canli ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur iki Part GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kur2 ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur-Tek Part GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kur' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur UEFI GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kuruefi ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg


grub-mkrescue $HOME/distro/iso/ -o $HOME/distro/distro.iso






