#!/usr/bin/env bash
version="6.6.0"
name="linux-libc-dev"
depends=""
description="temel dağıtım kernel dosyası ve libc"
source=""
groups="sys.base"
setup()
{
	echo ""
}
build()
{
	echo ""
}
package()
{
	cp -prfv $dizin/$name/usr  ${DESTDIR}/
	
}


