#!/usr/bin/env bash
name="networkmanager"
version="1.44.2"
description="network management daemon"
source="https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/archive/$version/NetworkManager-$version.tar.gz"
depends="libndp nss newt"
group=(net.misc)
unset CFLAGS
unset CXXFLAGS
setup(){
	cd $SOURCEDIR
	cp -prfv $dizin/$name/conf/*  ${SOURCEDIR}/
	
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsession_tracking=no \
        -Dsession_tracking_consolekit=false \
        -Dselinux=false \
        -Dpolkit=false \
        -Dcrypto=nss \
        -Dsystemd_journal=false \
        -Dsystemdsystemunitdir=no \
        -Dqt=false \
        -Dmodem_manager=false \
        -Dppp=true \
        -Dovs=true \
        -Dvapi=true \
        -Dtests=no
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    install -D -m644 $SOURCEDIRconf/networkmanager.initd "${DESTDIR}"/etc/init.d/networkmanager
    install -D -m644 $SOURCEDIRconf/networkmanager.conf "${DESTDIR}"/etc/NetworkManager/NetworkManager.conf
    install -D -m644 $SOURCEDIRconf/30-random-mac.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    install -D -m644 $SOURCEDIRconf/20-wifi-powersave.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
}

