#!/usr/bin/env bash
version="13.1.0"
name="gcc"
depends="glibc,binutils,libmpc,zlib,linux-headers"
description="DOS filesystem tools - provides mkdosfs, mkfs.msdos, mkfs.vfat"
source="https://ftp.gnu.org/gnu/gcc/gcc-${version}/gcc-${version}.tar.xz"
groups="sys.devel"
export CFLAGS="-O2 -s"
export CXXFLAGS="-O2 -s"
unset LDFLAGS
setup()
{
#cd $SOURCEDIR
	 options=(
      --prefix=/usr
      --libexecdir=/usr/libexec
      --mandir=/usr/share/man
      --infodir=/usr/share/info
      --enable-languages=c,c++
      --with-linker-hash-style=gnu
      --with-system-zlib
      --enable-__cxa_atexit
      --enable-cet=auto
      --enable-checking=release
      --enable-clocale=gnu
      --enable-default-pie
      --enable-default-ssp
      --enable-gnu-indirect-function
      --enable-gnu-unique-object
      --enable-libstdcxx-backtrace
      --enable-link-serialization=1
      --enable-linker-build-id
      --enable-lto
      --enable-multilib
      --enable-plugin
      --enable-shared
      --enable-threads=posix
      --disable-libssp
      --disable-libstdcxx-pch
      --disable-werror
      --without-zstd
      --disable-nls
    )
    cd $SOURCEDIR
	 mkdir build
    cd build
    ../configure ${options[@]} \
        --libdir=/usr/lib64 \
        --target=x86_64-pc-linux-gnu 
        #\
        #$(use_opt multilib "--enable-multilib" "") \
        #$(use_opt multilib "--with-multilib-list=m32,m64" "")
	
}
build()
{
	cd $SOURCEDIR/build
	make -j 2
}
package()
{
	cd $SOURCEDIR/build
	make install DESTDIR=${DESTDIR}
    	
    	
    	mkdir -p ${DESTDIR}/usr/lib64/
    	ln -s gcc ${DESTDIR}/usr/bin/cc
    	ln -s g++ ${DESTDIR}/usr/bin/cxx
    	cd $BUILDDIR
    	find ./ -iname "*" -exec strip -s {} \;
}


