#!/usr/bin/env bash
version="2.41"
name="binutils"
depends="glibc,zlib"
description="A set of programs to assemble and manipulate binary and object files"
source="https://ftp.gnu.org/gnu/binutils/binutils-$version.tar.xz"
groups="sys.devel"

setup()
{
	cd $SOURCEDIR
    ./configure --prefix=/usr \
          --libdir=/usr/lib64 \
          --sysconfdir=/etc
          
          #--disable-gdb \
          #--disable-gdbserver \
          #--disable-libdecnumber \
          #--disable-readline \
          #--disable-sim \
          # \
          
          
          #  --enable-x86_64-linux-gnu \
         # $(use_opt x86_64 --enable-targets=x86_64-linux-gnu,x86_64-linux-gnux32,x86_64-pep ) \
         # $(use_opt x86_64 --disable-x86-used-note )\
       
	
}
build()
{
cd $SOURCEDIR
	make 
}
package()
{
cd $SOURCEDIR
	make install  DESTDIR=$DESTDIR
}


